services:
  - type: worker
    name: discord-essence-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python discord_essence_bot.py
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: WP_API_URL
        sync: false
      - key: WP_BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.8
